<Project Sdk="Microsoft.NET.Sdk">
  <!-- Build with:  dotnet build -p:TtsManaged="<game folder>/Tabletop Simulator_Data/Managed" -->
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <RollForward>LatestMajor</RollForward>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MoonSharp.Interpreter">
      <HintPath>$(TtsManaged)\MoonSharp.Interpreter.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
